name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build:
    name: Build and publish release
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            cross: false
            strip: true
          - target: x86_64-unknown-linux-musl
            cross: true
            strip: true
          - target: i686-unknown-linux-gnu
            cross: true
            strip: true
          - target: i686-unknown-linux-musl
            cross: true
            strip: true
          - target: aarch64-unknown-linux-gnu
            cross: true
            strip: false
          - target: aarch64-unknown-linux-musl
            cross: true
            strip: false

    steps:
      - uses: actions/checkout@master
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}

      - name: Stamp version with commit hash
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          sed -i "s/^version = \"\(.*\)\"/version = \"\1+git.${SHORT_SHA}\"/" Cargo.toml
          echo "SHORT_SHA=${SHORT_SHA}" >> $GITHUB_ENV

      - name: Build binaries
        uses: ClementTsang/cargo-action@v0.0.6
        with:
          command: build
          args: --release --target=${{ matrix.target }}
          use-cross: ${{ matrix.cross }}

      - name: Strip binaries
        run: strip target/${{ matrix.target }}/release/mihoro
        if: ${{ matrix.strip }}

      - name: Package binaries
        run: |
          ARTIFACT="mihoro-${{ github.ref_name }}+git.${{ env.SHORT_SHA }}-${{ matrix.target }}.tar.gz"
          cd target/${{ matrix.target }}/release
          tar -czvf "$ARTIFACT" mihoro
          echo "ARTIFACT=$ARTIFACT" >> $GITHUB_ENV
          cd -

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.target }}/release/${{ env.ARTIFACT }}
          asset_name: ${{ env.ARTIFACT }}
          tag: ${{ github.ref_name }}
